### ISSUE TITLE
Filter out crossposts

### ISSUE THREAD

**Issue by maximumpeaches** [Nonlinear-EA/The-Nonlinear-Library#30]
Here is the email thread:

From Kat Woods:

... there's a glitch happening on the Nonlinear Library where if it's cross-posted to LessWrong or EA Forum, it'll create an episode that's just the intro and outro and no content. It's because of how the Forums have set things up and they're not going to be able to fix it anytime soon.

From Daniel:
There's already a per-channel filtering mechanism to avoid reposting so I'd say it'd be fairly easy for Max to scan other channel XMLs to avoid these empty crossposts.

From Kat Woods:

It's fine to have the episodes be dropped. The problem right now is that it still shows the dropped one, but just with the intro-outro and no content, so it's confusing for people, and they think it's not there. 

From Sharang:

Let me summarize the issue as I understand it, and you can ask any follow up questions to [@JP Addison](mailto:jp.addison@centreforeffectivealtruism.org) , who is the tech lead on the EA Forum.

Some time ago, we implemented a feature that allows crossposting between LessWrong and the EA Forum. The way this feature works is fetching the content of a post upon load from the other forum (e.g. loading an EA Forum post that was originally a LessWrong post pulls the content at load time - these contents are never stored in the EA Forum database). This architecture has caused a bunch of issues, and we actually plan to reimplement it in a way that does store the content in both databases. But for now, this means that the RSS feed has empty content for crossposts.

...Just want to give you a heads up that I expect this will take a bit longer for us to resolve. We're pretty focused on some projects around community discussion dynamics right now, and might not get to this for another few months (our priorities changed based on a bunch of important discussions we had after this last email).

That said, I was wondering whether it's actually OK to have cross-posted articles from LW get dropped from the EAF feed and vice versa? Since in the main NonLinear Library you'll still get one copy of the article?

**Comment by aarangop** [comment]
So apparently the post content is inside a description tag. 

This tag has html in it and usually the first thing is a 'Published on ...' string. It seems that cross-posts only have this string followed by a link to the original post and below a link to the discussion in the comments section. 

The scripts currently add the intro and outro to the content, but in some cases, since the content is just an href tag, which is not processed to audio by BeyondWords, we end up with an audio of the intro and outro only. 

In the new version of the scripts (since #31), which create the feed for BeyondWords, we check that each item's content has something in it. This is done by parsing the description text to html and checking whether there is more than one <p> tag. If an item has only one <p> tag, it is likely a cross-post so it is discarded. If the post is cross-posted from somewhere other than the EA, AF or LW forums, it won't make it to the podcast because we don't have the content for it.

**Comment by aarangop** [comment]
Sample of cross-post without content:

```
<description>
<![CDATA[Published on April 11, 2023 5:30 PM GMT<br/>
<br/>
<br/>
<br/>
<a href="https://forum.effectivealtruism.org/posts/rwWXFDA6gBJjXHBA9/request-to-agi-organizations-share-your-views-on-pausing-ai#comments">Discuss</a>]]>
</description>
```

**Comment by aarangop** [comment]
This has been addressed on the old and the new code.
